services:
  taxi_db:
    image: postgres:13
    container_name: taxi_db_server

    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - taxi_postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}"]
      interval: 10s
      retries: 5
      start_period: 5s
    restart: always

  pipeline:
    build: .
    container_name: taxi_pipeline_runner
    stdin_open: true
    tty: true
    env_file:
      - .env
    depends_on:
      - taxi_db
    volumes:
      - /mnt/c/Datasetw1:/app_week1/data
    restart: "no"

volumes:
  taxi_postgres_data:


