FROM apache/spark:3.5.7-java17-python3

USER root

COPY ./pyspark/ /opt/spark/work-dir/

USER spark

ENTRYPOINT ["/opt/spark/bin/spark-submit"]

CMD [ "--jars", "/opt/spark/work-dir/postgresql-42.7.10.jar", "/opt/spark/work-dir/spark_main.py" ]