apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod
  labels:
    app: postgres-db
spec:
  containers:
    - name: postgres-db-container
      image: postgres:15
      ports:
        - containerPort: 5432
      envFrom:
        - secretRef:
            name: db-secret

---

apiVersion: v1
kind: Service
metadata:
  name: postgresdb-service
spec:
  selector:
    app: postgres-db
  ports:
    - port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: Pod
metadata:
  name: fastapi-pod
  labels:
    app: fastapi
spec:
  containers:
    - name: fastapi-container
      image: week1-taxi-api:v3
      imagePullPolicy: Never
      ports:
        - containerPort: 8000
      envFrom:
        - secretRef:
            name: db-secret

---

apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  selector:
    app: fastapi
  ports:
    - port: 8000
      targetPort: 8000

---

apiVersion: v1
kind: Pod
metadata:
  name: redis-pod
  labels:
    app: redis-cache
spec:
  containers:
    - name: redis-container
      image: redis:8.4
      imagePullPolicy: Never
      ports:
        - containerPort: 6379

---

apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis-cache
  ports:
    - port: 6379
      targetPort: 6379

---

apiVersion: batch/v1
kind: Job
metadata:
  name: spark-etl-job
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
        - name: spark-container
          image: taxi-spark-kube-job:v2
          imagePullPolicy: Never
          volumeMounts:
            - name: data-volume
              mountPath: /opt/spark/data
      volumes:
        - name: data-volume
          hostPath:
            path: /minikube-data
      restartPolicy: Never